### ISSUE TITLE
Conferência da robustez do aplicativo

### ISSUE THREAD

**Issue by Gab-HSP** [DisciplinasProgramacao/projeto3-titas#50]

**Comment by Gab-HSP** [comment]
Bugs encontrados:

- Na opção "Informe a opção desejada", de diversos métodos, se for inserido um número que não faz parte do array, é lançada uma ArrayIndexOutOfBoundsException e o programa é automaticamente salvo.
- Ao buscar nomes de clientes e placas de veículos, o programa diferencia letras maiúsculas e minúsculas, não encontrando aquele cliente ou placa.
- Ao consultar o histórico de um cliente, são pedidas as datas inicial e final, mas ela não verifica se a data final vem mesmo após a inicial, ou quantos dias cada mês possui.

**Comment by lucaazalim** [comment]
Erros mencionados acima corrigidos.
